version: "3"

services:
   frontend:
       build: ghcr.io/wolf-361/portfolio:main
       restart: unless-stopped
       ports:
          - 127.0.0.1:80:80
   backend:
      build: backend
      restart: unless-stopped
      ports:
         - 127.0.0.1:5000:5000