# First stage: build the app
FROM node:18

WORKDIR /app

# Copy all the files from the current directory to the working directory
COPY . .

# Install all the dependencies
RUN npm install --prefix ./ 

# Second stage: serve the app
CMD [ "node", "index.js" ]